export const SET_NUM_OF_QUESTIONS = 'SET_NUM_OF_QUESTIONS';
export const SET_QUESTIONS = 'SET_QUESTIONS';
export const SET_LETTER = 'SET_LETTER';
export const EDIT_COMMENTS = 'EDIT_COMMENTS';
export const SET_TEST = 'SET_TEST';
export const SET_CLASSROOM = 'SET_CLASSROOM';